services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - user-service
      - task-service
      - admin-service
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  user-service:
    build: ./user-service
    restart: unless-stopped
    environment:
      - PORT=8080
    volumes:
      - ./user-service/data:/app/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 2

  task-service:
    build: ./task-service
    restart: unless-stopped
    environment:
      - PORT=9090
    volumes:
      - ./task-service/data:/app/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 2

  admin-service:
    build: ./admin-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx-logs:/var/log/nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge
