services:
  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    environment:
      - PORT=8080
    volumes:
      - ./user-service/data:/app/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1

  task-service:
    build: ./task-service
    container_name: task-service
    restart: unless-stopped
    environment:
      - PORT=9090
    volumes:
      - ./task-service/data:/app/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - task-service
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  backend:
    driver: bridge
